In [1]:
import pandas as pd
import numpy as np

In [2]:
#data=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data')
#data.to_csv('e:\car.data')
data=pd.read_csv('F:\car.data')
data.dtypes

Unnamed: 0     int64
vhigh         object
vhigh.1       object
2             object
2.1           object
small         object
low           object
unacc         object
dtype: object

In [3]:
data.head()

   Unnamed: 0  vhigh vhigh.1  2 2.1  small   low  unacc
0           0  vhigh   vhigh  2   2  small   med  unacc
1           1  vhigh   vhigh  2   2  small  high  unacc
2           2  vhigh   vhigh  2   2    med   low  unacc
3           3  vhigh   vhigh  2   2    med   med  unacc
4           4  vhigh   vhigh  2   2    med  high  unacc

In [4]:
data.drop(['Unnamed: 0'],axis=1,inplace=True)
data

      vhigh vhigh.1      2   2.1  small   low  unacc
0     vhigh   vhigh      2     2  small   med  unacc
1     vhigh   vhigh      2     2  small  high  unacc
2     vhigh   vhigh      2     2    med   low  unacc
3     vhigh   vhigh      2     2    med   med  unacc
4     vhigh   vhigh      2     2    med  high  unacc
5     vhigh   vhigh      2     2    big   low  unacc
6     vhigh   vhigh      2     2    big   med  unacc
7     vhigh   vhigh      2     2    big  high  unacc
8     vhigh   vhigh      2     4  small   low  unacc
9     vhigh   vhigh      2     4  small   med  unacc
10    vhigh   vhigh      2     4  small  high  unacc
11    vhigh   vhigh      2     4    med   low  unacc
12    vhigh   vhigh      2     4    med   med  unacc
13    vhigh   vhigh      2     4    med  high  unacc
14    vhigh   vhigh      2     4    big   low  unacc
15    vhigh   vhigh      2     4    big   med  unacc
16    vhigh   vhigh      2     4    big  high  unacc
17    vhigh   vhigh      2  more  small   low  unacc
18    vhigh   vhigh      2  more  small   med  unacc
19    vhigh   vhigh      2  more  small  high  unacc
20    vhigh   vhigh      2  more    med   low  unacc
21    vhigh   vhigh      2  more    med   med  unacc
22    vhigh   vhigh      2  more    med  high  unacc
23    vhigh   vhigh      2  more    big   low  unacc
24    vhigh   vhigh      2  more    big   med  unacc
25    vhigh   vhigh      2  more    big  high  unacc
26    vhigh   vhigh      3     2  small   low  unacc
27    vhigh   vhigh      3     2  small   med  unacc
28    vhigh   vhigh      3     2  small  high  unacc
29    vhigh   vhigh      3     2    med   low  unacc
...     ...     ...    ...   ...    ...   ...    ...
1697    low     low      4  more    big   low  unacc
1698    low     low      4  more    big   med   good
1699    low     low      4  more    big  high  vgood
1700    low     low  5more     2  small   low  unacc
1701    low     low  5more     2  small   med  unacc
1702    low     low  5more     2  small  high  unacc
1703    low     low  5more     2    med   low  unacc
1704    low     low  5more     2    med   med  unacc
1705    low     low  5more     2    med  high  unacc
1706    low     low  5more     2    big   low  unacc
1707    low     low  5more     2    big   med  unacc
1708    low     low  5more     2    big  high  unacc
1709    low     low  5more     4  small   low  unacc
1710    low     low  5more     4  small   med    acc
1711    low     low  5more     4  small  high   good
1712    low     low  5more     4    med   low  unacc
1713    low     low  5more     4    med   med   good
1714    low     low  5more     4    med  high  vgood
1715    low     low  5more     4    big   low  unacc
1716    low     low  5more     4    big   med   good
1717    low     low  5more     4    big  high  vgood
1718    low     low  5more  more  small   low  unacc
1719    low     low  5more  more  small   med    acc
1720    low     low  5more  more  small  high   good
1721    low     low  5more  more    med   low  unacc
1722    low     low  5more  more    med   med   good
1723    low     low  5more  more    med  high  vgood
1724    low     low  5more  more    big   low  unacc
1725    low     low  5more  more    big   med   good
1726    low     low  5more  more    big  high  vgood

[1727 rows x 7 columns]

In [5]:
attr=['buying', 'maint' , 'doors','persons','lug_boot' ,'safety']+['class']
data.columns=[i for i in attr]

In [6]:
data.head()

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    med  unacc
1  vhigh  vhigh     2       2    small   high  unacc
2  vhigh  vhigh     2       2      med    low  unacc
3  vhigh  vhigh     2       2      med    med  unacc
4  vhigh  vhigh     2       2      med   high  unacc

In [7]:
data=data.replace('vhigh',1)
data=data.replace('high',2)
data=data.replace('med',3)
data=data.replace('low',4)
data=data.replace('5more',6)
data=data.replace('more',5)
data=data.replace('small',1)
data=data.replace('med',3)
data=data.replace('big',2)
data=data.replace('unacc',1)
data=data.replace('acc',2)
data=data.replace('good',3)
data=data.replace('vgood',4)

In [8]:
data

      buying  maint doors persons  lug_boot  safety  class
0          1      1     2       2         1       3      1
1          1      1     2       2         1       2      1
2          1      1     2       2         3       4      1
3          1      1     2       2         3       3      1
4          1      1     2       2         3       2      1
5          1      1     2       2         2       4      1
6          1      1     2       2         2       3      1
7          1      1     2       2         2       2      1
8          1      1     2       4         1       4      1
9          1      1     2       4         1       3      1
10         1      1     2       4         1       2      1
11         1      1     2       4         3       4      1
12         1      1     2       4         3       3      1
13         1      1     2       4         3       2      1
14         1      1     2       4         2       4      1
15         1      1     2       4         2       3      1
16         1      1     2       4         2       2      1
17         1      1     2       5         1       4      1
18         1      1     2       5         1       3      1
19         1      1     2       5         1       2      1
20         1      1     2       5         3       4      1
21         1      1     2       5         3       3      1
22         1      1     2       5         3       2      1
23         1      1     2       5         2       4      1
24         1      1     2       5         2       3      1
25         1      1     2       5         2       2      1
26         1      1     3       2         1       4      1
27         1      1     3       2         1       3      1
28         1      1     3       2         1       2      1
29         1      1     3       2         3       4      1
...      ...    ...   ...     ...       ...     ...    ...
1697       4      4     4       5         2       4      1
1698       4      4     4       5         2       3      3
1699       4      4     4       5         2       2      4
1700       4      4     6       2         1       4      1
1701       4      4     6       2         1       3      1
1702       4      4     6       2         1       2      1
1703       4      4     6       2         3       4      1
1704       4      4     6       2         3       3      1
1705       4      4     6       2         3       2      1
1706       4      4     6       2         2       4      1
1707       4      4     6       2         2       3      1
1708       4      4     6       2         2       2      1
1709       4      4     6       4         1       4      1
1710       4      4     6       4         1       3      2
1711       4      4     6       4         1       2      3
1712       4      4     6       4         3       4      1
1713       4      4     6       4         3       3      3
1714       4      4     6       4         3       2      4
1715       4      4     6       4         2       4      1
1716       4      4     6       4         2       3      3
1717       4      4     6       4         2       2      4
1718       4      4     6       5         1       4      1
1719       4      4     6       5         1       3      2
1720       4      4     6       5         1       2      3
1721       4      4     6       5         3       4      1
1722       4      4     6       5         3       3      3
1723       4      4     6       5         3       2      4
1724       4      4     6       5         2       4      1
1725       4      4     6       5         2       3      3
1726       4      4     6       5         2       2      4

[1727 rows x 7 columns]

In [9]:
car = data.values

In [10]:
car

array([[1, 1, '2', ..., 1, 3, 1],
       [1, 1, '2', ..., 1, 2, 1],
       [1, 1, '2', ..., 3, 4, 1],
       ...,
       [4, 4, 6, ..., 2, 4, 1],
       [4, 4, 6, ..., 2, 3, 3],
       [4, 4, 6, ..., 2, 2, 4]], dtype=object)

In [11]:
x,y=car[:,:6],car[:,6]

In [12]:
x

array([[1, 1, '2', '2', 1, 3],
       [1, 1, '2', '2', 1, 2],
       [1, 1, '2', '2', 3, 4],
       ...,
       [4, 4, 6, 5, 2, 4],
       [4, 4, 6, 5, 2, 3],
       [4, 4, 6, 5, 2, 2]], dtype=object)

In [13]:
y

array([1, 1, 1, ..., 1, 3, 4], dtype=object)

In [14]:
#car.astype(int)
x,y = x.astype(int), y.astype(int)

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,test_size=0.2)
from sklearn.neighbors import KNeighborsClassifier
algo=KNeighborsClassifier()
algo.fit(x_train,y_train)
#print(algo.predict([x]))#requires dimension less tha equals to 2
print(algo.score(x_test,y_test))

0.921965317919