In [51]:
import pandas as pd
import numpy as np
dt=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/lung-cancer/lung-cancer.data')
dt

,1,0,3,0.1,?,0.2,2,2.1,2.2,1.1,...,2.25,2.26,2.27,2.28,2.29,1.12,1.13,1.14,2.30,2.31
0,1,0,3,3,1,0,3,1,3,1,...,2,2,2,2,2,2,2,1,2,2
1,1,0,3,3,2,0,3,3,3,1,...,2,2,2,2,2,2,2,2,1,2
2,1,0,2,3,2,1,3,3,3,1,...,2,2,2,2,2,2,2,2,2,2
3,1,0,3,2,1,1,3,3,3,2,...,2,2,2,2,2,2,2,1,2,2
4,1,0,3,3,2,0,3,3,3,1,...,2,2,2,2,2,2,2,2,1,2
5,1,0,3,2,1,0,3,3,3,1,...,2,2,2,2,1,2,2,2,1,2
6,1,0,2,2,1,0,3,1,3,3,...,2,2,1,2,2,2,2,1,2,2
7,1,0,3,1,1,0,3,1,3,1,...,2,2,2,2,2,2,2,1,2,2
8,2,0,2,3,2,0,2,2,2,1,...,2,2,2,1,3,2,1,1,2,2
9,2,0,2,2,0,0,3,2,3,1,...,2,2,2,2,2,2,2,2,2,2
10,2,0,2,3,2,0,1,2,1,1,...,2,2,2,2,2,1,1,2,2,1
11,2,0,2,1,1,0,1,2,2,1,...,2,2,2,2,2,2,2,1,2,2
12,2,0,2,2,1,1,2,3,3,1,...,2,2,2,2,2,1,1,1,2,2
13,2,1,3,0,?,1,1,2,2,1,...,2,2,2,2,2,2,2,1,2,1
14,2,0,3,2,2,1,2,2,2,1,...,2,2,2,2,2,2,2,2,2,2
15,2,0,3,2,2,0,1,1,3,1,...,2,2,2,2,2,2,2,1,2,2
16,2,0,2,1,1,0,2,1,3,1,...,2,2,2,2,2,1,1,1,2,2
17,2,0,2,0,?,0,2,3,3,3,...,2,2,2,2,2,2,2,2,1,2
18,2,0,1,2,1,0,3,3,3,1,...,2,2,2,2,2,1,1,2,2,1
19,2,0,2,0,?,1,3,3,3,1,...,2,2,2,2,1,2,2,1,2,2
20,2,0,3,3,2,0,2,1,3,1,...,2,2,1,2,2,2,2,2,1,2
21,3,0,2,3,1,1,2,2,1,1,...,3,3,3,3,1,3,3,2,2,1
22,3,0,2,3,1,1,1,2,1,1,...,2,2,2,2,2,2,2,2,2,1
23,3,0,3,3,1,0,3,3,1,1,...,2,2,2,2,3,2,2,2,2,1
24,3,0,2,3,2,0,1,2,2,1,...,2,2,2,1,3,1,2,2,1,2
25,3,0,2,2,2,0,2,1,2,1,...,2,2,2,2,2,2,2,1,2,1
26,3,0,2,2,1,0,2,2,2,1,...,3,3,2,2,3,2,2,2,2,1
27,3,0,3,2,2,0,2,2,2,1,...,2,2,2,3,1,2,2,2,2,2
28,3,0,2,1,1,0,2,2,1,1,...,2,2,3,2,2,2,2,2,2,1
29,3,0,2,3,2,1,2,2,3,1,...,2,2,2,2,2,2,2,1,2,2
30,3,0,2,3,1,0,2,3,3,1,...,2,2,2,2,2,2,2,2,2,2

In [52]:
cols=['class','a1','a2','a3','a4','a5','a6','a7','a8','a9','a10','a11','a12','a13','a14','a15','a16','a17','a18','a19','a20','a21','a22','a23','a24','a25','a26','a27','a28','a29','a30','a31','a32','a33','a34','a35','a36','a37','a38','a39','a40','a41','a42','a43','a44','a45','a46','a47','a48','a49','a50','51','52','53','54','55','56']
dt.columns=[i for i in cols]
dt

,class,a1,a2,a3,a4,a5,a6,a7,a8,a9,...,a47,a48,a49,a50,51,52,53,54,55,56
0,1,0,3,3,1,0,3,1,3,1,...,2,2,2,2,2,2,2,1,2,2
1,1,0,3,3,2,0,3,3,3,1,...,2,2,2,2,2,2,2,2,1,2
2,1,0,2,3,2,1,3,3,3,1,...,2,2,2,2,2,2,2,2,2,2
3,1,0,3,2,1,1,3,3,3,2,...,2,2,2,2,2,2,2,1,2,2
4,1,0,3,3,2,0,3,3,3,1,...,2,2,2,2,2,2,2,2,1,2
5,1,0,3,2,1,0,3,3,3,1,...,2,2,2,2,1,2,2,2,1,2
6,1,0,2,2,1,0,3,1,3,3,...,2,2,1,2,2,2,2,1,2,2
7,1,0,3,1,1,0,3,1,3,1,...,2,2,2,2,2,2,2,1,2,2
8,2,0,2,3,2,0,2,2,2,1,...,2,2,2,1,3,2,1,1,2,2
9,2,0,2,2,0,0,3,2,3,1,...,2,2,2,2,2,2,2,2,2,2
10,2,0,2,3,2,0,1,2,1,1,...,2,2,2,2,2,1,1,2,2,1
11,2,0,2,1,1,0,1,2,2,1,...,2,2,2,2,2,2,2,1,2,2
12,2,0,2,2,1,1,2,3,3,1,...,2,2,2,2,2,1,1,1,2,2
13,2,1,3,0,?,1,1,2,2,1,...,2,2,2,2,2,2,2,1,2,1
14,2,0,3,2,2,1,2,2,2,1,...,2,2,2,2,2,2,2,2,2,2
15,2,0,3,2,2,0,1,1,3,1,...,2,2,2,2,2,2,2,1,2,2
16,2,0,2,1,1,0,2,1,3,1,...,2,2,2,2,2,1,1,1,2,2
17,2,0,2,0,?,0,2,3,3,3,...,2,2,2,2,2,2,2,2,1,2
18,2,0,1,2,1,0,3,3,3,1,...,2,2,2,2,2,1,1,2,2,1
19,2,0,2,0,?,1,3,3,3,1,...,2,2,2,2,1,2,2,1,2,2
20,2,0,3,3,2,0,2,1,3,1,...,2,2,1,2,2,2,2,2,1,2
21,3,0,2,3,1,1,2,2,1,1,...,3,3,3,3,1,3,3,2,2,1
22,3,0,2,3,1,1,1,2,1,1,...,2,2,2,2,2,2,2,2,2,1
23,3,0,3,3,1,0,3,3,1,1,...,2,2,2,2,3,2,2,2,2,1
24,3,0,2,3,2,0,1,2,2,1,...,2,2,2,1,3,1,2,2,1,2
25,3,0,2,2,2,0,2,1,2,1,...,2,2,2,2,2,2,2,1,2,1
26,3,0,2,2,1,0,2,2,2,1,...,3,3,2,2,3,2,2,2,2,1
27,3,0,3,2,2,0,2,2,2,1,...,2,2,2,3,1,2,2,2,2,2
28,3,0,2,1,1,0,2,2,1,1,...,2,2,3,2,2,2,2,2,2,1
29,3,0,2,3,2,1,2,2,3,1,...,2,2,2,2,2,2,2,1,2,2
30,3,0,2,3,1,0,2,3,3,1,...,2,2,2,2,2,2,2,2,2,2

In [53]:
dt.a4=dt.a4.replace('?',-1)
dt.a38=dt.a38.replace('?',4)
dt,dt['a38']

(    class  a1  a2  a3  a4  a5  a6  a7  a8  a9 ...  a47  a48  a49  a50  51  52  \
 0       1   0   3   3   1   0   3   1   3   1 ...    2    2    2    2   2   2
 1       1   0   3   3   2   0   3   3   3   1 ...    2    2    2    2   2   2
 2       1   0   2   3   2   1   3   3   3   1 ...    2    2    2    2   2   2
 3       1   0   3   2   1   1   3   3   3   2 ...    2    2    2    2   2   2
 4       1   0   3   3   2   0   3   3   3   1 ...    2    2    2    2   2   2
 5       1   0   3   2   1   0   3   3   3   1 ...    2    2    2    2   1   2
 6       1   0   2   2   1   0   3   1   3   3 ...    2    2    1    2   2   2
 7       1   0   3   1   1   0   3   1   3   1 ...    2    2    2    2   2   2
 8       2   0   2   3   2   0   2   2   2   1 ...    2    2    2    1   3   2
 9       2   0   2   2   0   0   3   2   3   1 ...    2    2    2    2   2   2
 10      2   0   2   3   2   0   1   2   1   1 ...    2    2    2    2   2   1
 11      2   0   2   1   1   0   1   2   2   1 ...    2    2    2    2   2   2
 12      2   0   2   2   1   1   2   3   3   1 ...    2    2    2    2   2   1
 13      2   1   3   0  -1   1   1   2   2   1 ...    2    2    2    2   2   2
 14      2   0   3   2   2   1   2   2   2   1 ...    2    2    2    2   2   2
 15      2   0   3   2   2   0   1   1   3   1 ...    2    2    2    2   2   2
 16      2   0   2   1   1   0   2   1   3   1 ...    2    2    2    2   2   1
 17      2   0   2   0  -1   0   2   3   3   3 ...    2    2    2    2   2   2
 18      2   0   1   2   1   0   3   3   3   1 ...    2    2    2    2   2   1
 19      2   0   2   0  -1   1   3   3   3   1 ...    2    2    2    2   1   2
 20      2   0   3   3   2   0   2   1   3   1 ...    2    2    1    2   2   2
 21      3   0   2   3   1   1   2   2   1   1 ...    3    3    3    3   1   3
 22      3   0   2   3   1   1   1   2   1   1 ...    2    2    2    2   2   2
 23      3   0   3   3   1   0   3   3   1   1 ...    2    2    2    2   3   2
 24      3   0   2   3   2   0   1   2   2   1 ...    2    2    2    1   3   1
 25      3   0   2   2   2   0   2   1   2   1 ...    2    2    2    2   2   2
 26      3   0   2   2   1   0   2   2   2   1 ...    3    3    2    2   3   2
 27      3   0   3   2   2   0   2   2   2   1 ...    2    2    2    3   1   2
 28      3   0   2   1   1   0   2   2   1   1 ...    2    2    3    2   2   2
 29      3   0   2   3   2   1   2   2   3   1 ...    2    2    2    2   2   2
 30      3   0   2   3   1   0   2   3   3   1 ...    2    2    2    2   2   2

     53  54  55  56
 0    2   1   2   2
 1    2   2   1   2
 2    2   2   2   2
 3    2   1   2   2
 4    2   2   1   2
 5    2   2   1   2
 6    2   1   2   2
 7    2   1   2   2
 8    1   1   2   2
 9    2   2   2   2
 10   1   2   2   1
 11   2   1   2   2
 12   1   1   2   2
 13   2   1   2   1
 14   2   2   2   2
 15   2   1   2   2
 16   1   1   2   2
 17   2   2   1   2
 18   1   2   2   1
 19   2   1   2   2
 20   2   2   1   2
 21   3   2   2   1
 22   2   2   2   1
 23   2   2   2   1
 24   2   2   1   2
 25   2   1   2   1
 26   2   2   2   1
 27   2   2   2   2
 28   2   2   2   1
 29   2   1   2   2
 30   2   2   2   2

 [31 rows x 57 columns], 0     1
 1     2
 2     2
 3     1
 4     1
 5     2
 6     1
 7     2
 8     2
 9     2
 10    2
 11    2
 12    1
 13    2
 14    2
 15    2
 16    1
 17    1
 18    1
 19    2
 20    2
 21    1
 22    3
 23    2
 24    4
 25    2
 26    1
 27    1
 28    3
 29    2
 30    2
 Name: a38, dtype: object)

In [54]:
dt1=dt.drop('class',axis=1)
x=np.array(dt1)
y=np.array(dt['class'])
x,y

(array([[0, 3, 3, ..., 1, 2, 2],
        [0, 3, 3, ..., 2, 1, 2],
        [0, 2, 3, ..., 2, 2, 2],
        ...,
        [0, 2, 1, ..., 2, 2, 1],
        [0, 2, 3, ..., 1, 2, 2],
        [0, 2, 3, ..., 2, 2, 2]], dtype=object),
 array([1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3], dtype=int64))

In [55]:
#from sklearn.decomposition import PCA
#al=PCA(n_components=56)
#al.fit(x)

In [136]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.85,test_size=0.15)
from sklearn.neighbors import KNeighborsClassifier
algo=KNeighborsClassifier(20)
algo.fit(x_train,y_train)
algo.score(x_test,y_test)

0.4

In [133]:
from sklearn.model_selection import train_test_split
from sklearn import metrics
k_range=range(1,20)
scores={}
scores_list=[]
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,test_size=0.2)
from sklearn.neighbors import KNeighborsClassifier
for k in k_range:
    algo=KNeighborsClassifier(n_neighbors=k)
    algo.fit(x_train,y_train)
    y_pred=algo.predict(x_test)
    scores[k]=metrics.accuracy_score(y_test,y_pred)
    scores_list.append(metrics.accuracy_score(y_test,y_pred))
scores,scores_list

({1: 0.7142857142857143,
  2: 0.7142857142857143,
  3: 0.42857142857142855,
  4: 0.7142857142857143,
  5: 0.5714285714285714,
  6: 0.5714285714285714,
  7: 0.42857142857142855,
  8: 0.5714285714285714,
  9: 0.2857142857142857,
  10: 0.42857142857142855,
  11: 0.42857142857142855,
  12: 0.42857142857142855,
  13: 0.42857142857142855,
  14: 0.42857142857142855,
  15: 0.42857142857142855,
  16: 0.42857142857142855,
  17: 0.42857142857142855,
  18: 0.42857142857142855,
  19: 0.42857142857142855},
 [0.7142857142857143,
  0.7142857142857143,
  0.42857142857142855,
  0.7142857142857143,
  0.5714285714285714,
  0.5714285714285714,
  0.42857142857142855,
  0.5714285714285714,
  0.2857142857142857,
  0.42857142857142855,
  0.42857142857142855,
  0.42857142857142855,
  0.42857142857142855,
  0.42857142857142855,
  0.42857142857142855,
  0.42857142857142855,
  0.42857142857142855,
  0.42857142857142855,
  0.42857142857142855])

In [134]:
n=len(scores_list)

In [135]:
s=0
for i in scores_list:
    s=s+i
print(s/n)

0.48872180451127833

In [114]:

import keras
keras.__version__

'2.2.5'

In [31]:
import tensorflow
tensorflow.__version__

'1.13.1'

In [32]:
import sklearn
sklearn.__version__

'0.21.2'